### ISSUE TITLE
Figure out why we're getting the class error

### ISSUE THREAD

**Issue by eceja2024** [nishilfaldu/alterna-canvas#57]
This error is occurring on the Dashboard and on the Announcements page.
![image](https://github.com/nishilfaldu/alterna-canvas/assets/56894514/f82686f5-ec65-4b39-aecc-0901938cf92e)

**Comment by athulyaganesh** [comment]
i updated the antd package and that seemed to make the class v className error go wat on the Dashboard, I assume its because an older version of antd uses class instead of className in their implementation? 

Still persists on the Announcements page though, despite updating react, useState and antd ://///

**Comment by eceja2024** [comment]
@athulyaganesh @nishilfaldu @AnushaChitranshi I don't believe it's causing any issues, and I'm worried that updating ant (and other packages) could mess up our app. I'm all for just ignoring this error. What do you all think?

**Comment by athulyaganesh** [comment]
I'm good with ignoring, didn't really cause a massive problem in our deployment (atleast I hope, @nishilfaldu can say more)

**Comment by nishilfaldu** [comment]
I am good to ignore too as deployment seems fine. It seems like a vite error and vite has been kinda annoying for quite a few things. It's the .vite/deps folder which was kinda an issue in deployment as well and had to find a hacky way around it

**Comment by athulyaganesh** [comment]
Ok, closing this issue for now. Will revisit in the future if need be.
